config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :projects do
    member do
      put 'order'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :utilized, presence: true
  validates :url, presence: true
  validates :git_url, presence: true

  mount_uploader :preview, ThumbnailUploader

  include RankedModel
  ranks :row_order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validate :validate_username
  validates_uniqueness_of :username
  validates_uniqueness_of :email

  attr_writer :login

  def login
    @login || self.username || self.email
  end


  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  
  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :order]
  

  

  def index
    @projects = Project.all
    @project = Project.new
  end

  def new
    if current_user.admin?
      @project = Project.new
    end
  end

  
  def edit
    if current_user.admin?
      @project = Project.find(params[:id])
    end
  end

  def destroy
    if current_user.admin?
      @project = Project.find(params[:id])
      @project.destroy
      redirect_to projects_path
    end
  end

  def order
    if current_user.admin?
      @project = Project.find(params[:id])
      @project.update_attributes(project_params)
      render plain: 'updated!'
    end
  end

  def update
    if current_user.admin?
      @project = Project.find(params[:id])
      @project.update_attributes(project_params)
      redirect_to projects_path
    end
  end
  
  def create
    @project = Project.create(project_params)
    if @project.invalid?
      flash[:error] = '<strong>Could not save </strong> the data entered is invalid.'
    end
    redirect_to projects_path
  end

private

  def project_params
    params.require(:project).permit(:title, :description, :utilized, :preview, :url, :git_url, :row_order_position, :viewable_heroku)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Robert Adame - Full Stack Web Developer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      
      <%= link_to 'Robert Adame', root_path, class: 'navbar-brand' %>
      
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#profileToggler" aria-controls="profileToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

            
      <div class="collapse navbar-collapse" id="profileToggler">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to 'Projects', projects_path, class: 'nav-link' %>                
          </li>
          <li class="nav-item">
            <%= link_to "GitHub", 'https://github.com/radamejr', class: 'nav-link', target: :_blank %>                
          </li>
          <li class="nav-item">
            <%= link_to "LinkedIn", 'https://www.linkedin.com/in/radamejr/', class: 'nav-link', target: :_blank %>  
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path , method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <br class="clear" />

    <div class="wrapper">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
      <%= yield %>
    </div>
   

    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-6 offset-1">

          </div>
          <div class="col-6 offset-1">
            <p>Profiles</p>
            <%= link_to "GitHub", 'https://github.com/radamejr', target: :_blank %>
            <br />
            <%= link_to "LinkedIn", 'https://www.linkedin.com/in/radamejr/', target: :_blank %>
          </div>
        </div>
      </div>
    </div>


  </body>
</html>

app/views/projects/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1> EDIT A PROJECT</h1>
  <%= simple_form_for @project do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :utilized %>
    <%= f.input :url %>
    <%= f.input :viewable_heroku %>
    <%= f.input :git_url %>
    <%= f.file_field :preview %>
    <%= f.submit 'Edit Project', class: 'btn btn-primary float-right' %>
    
  <% end %>
</div>

app/views/projects/index.html.erb
<!-- Modal -->
<div class="modal fade" id="projectModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a Project</h4>
      </div>
      <%= simple_form_for Project.new do |f| %>
      <div class="modal-body">
        
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :utilized %>
          <%= f.input :viewable_heroku %>
          <%= f.input :url %>
          <%= f.input :git_url %>
          <%= f.file_field :preview %>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit 'Add Project', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<br>
<ul class="col-10 offset-1 project-list" style="list-style-type: none">
  <% @projects.rank(:row_order).each do |project| %>

    <li data-update-url="<%= project_path(project) %>", class="booyah-box col-10 offset-1 project-box">
      <div class="row">
        <div class="col-sm-7">
          <h1><%= project.title %></h1><br />
          <p><%= project.description %></p><br />
          <h5>Languages and Resources utilized:</h5>
          <p><%= project.utilized %></p><br />
        </div>
        <div class="column col-sm-5 d-none d-sm-none d-md-block">
        <% if project.preview.present? %>
          <%= image_tag project.preview.url, class: 'img-fluid' %> 
        <% end %>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <div>
              <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-primary' %>
              <%= link_to 'Begone Project!', project_path(project), method: :delete, data: {confirm: 'You really want to delete this?'}, class: 'btn btn-danger' %>
            </div>
          <% end %>
        <% end %>
        <br />
        <br />
        <br />
        <% if project.viewable_heroku %>
          <%= link_to 'Demo', project.url, :class => "btn btn-outline-light", target: :_blank %></button>
        <% else %>
          <%= link_to 'API Only', project.url, :class => "btn btn-outline-light disabled", target: :_blank %></button>
        <% end %>
        <%= link_to 'GitHub', project.git_url, :class => "btn btn-outline-light", target: :_blank %></button>
        </div>
      </div>
      <br/>
      <br/>
      

  <% end %>

  
</ul>

<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li class="float-right">
      <%= link_to '#', data: {toggle: 'modal', target: '#projectModal'} , class: 'btn btn-primary' do %>
      Add Project
      <% end %>
    </li>
  <% end %>
<% end %>
<br />
<br />
<br />

<script>
  $(function() {
      $('.project-list').sortable({
        update: function( event, ui) {
          $.ajax({
            type: 'PUT',
            url: ui.item.data('update-url'),
            dataType: 'json',
            data: {project: { row_order_position: ui.item.index() } }
          });
        }
      });
  });
</script>

app/views/projects/new.html.erb
<div class="booyah-box col-10 offset-1">
  <%= simple_form_for Project.new do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :utilized %>
    <%= f.input :url %>

    <%= f.file_field :preview %>
    <%= f.submit 'Add Project', class: 'btn btn-primary' %>
  <% end %>
</div>

<%= link_to 'Add project' , '#', data: {toggle: 'modal', target: '#projectModal'} , class: 'btn btn-primary' %>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#projectModal">
  Add Project
</button>


<!-- Modal -->
<div class="modal fade" id="projectModal" tabindex="-1" role="dialog" aria-labelledby="projectModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="projectModal">Add a Project</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for Project.new do |f| %>
      <div class="modal-body">
        
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :utilized %>
          <%= f.input :url %>
          
          <%= f.file_field :preview %>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit 'Add Project', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="booyah-layout col-10 offset-1">
  <div class="intro">
    <!--<%= image_tag 'me.jpg', class: "me" %>-->
    <h1 class="name">Robert Adame</h1>
    <h2 class="title">Full Stack Web Developer</h2>
    <p class="about col-10 offset-1">I am a growing Full Stack Web Developer. Previously I have made a successful career of working for industry leading companies such as Dexcom and supporting their end consumers. This includes direct consumer interactions and also paving the way for new employees by supervising teams, running training classes and developing world class training materials.</p>
  </div>
  <br />
  <br />

  <div class="guidance">
    <p class="suggest col-10 offset-1">Please feel free to check out my current <%= link_to 'projects', projects_path %>. You will find a range of projects utilizing different skills that I have developed including use of: Ruby on Rails, PostgreSQL, JavaScript, Node/React, Bootstrap, HTML and CSS. Additionally there is also links directly to the Applications in their live environments and the GitHub repositories</p>

    <br />
    <br />

    <p class="business col-10 offset-1">If you have a business inquiry reach out to me at my email <a href="mailto:radamejr@gmail.com" class="contact-link">radamejr@gmail.com</a> You can also download a copy of <%= link_to "my resume", asset_path("Adame_Robert_-_Resume.docx.pdf"), target: :_blank %> or visit my <%= link_to "GitHub", 'https://github.com/radamejr', target: :_blank %> and <%= link_to "LinkedIn", 'https://www.linkedin.com/in/radamejr/', target: :_blank %> profiles.
      
    </p>


  </div>
  <br />
  <br />


</div>